### ISSUE TITLE
Hardcoded Paths

### ISSUE THREAD

**Issue by hgoodrow** [dansand71/OSSonAzure#1]
I didn't follow your instructions exactly so I cloned in to a $home/azdemosrc directory and ran the 1-build-environment.sh script.  It finished running the Azure CLI, created the VM but bombed out during the Ansible install.  It looks like the paths are hardcoded vs passed as parameters. 

--------------------------------------------
Ensuring we are in the /source directory for Ansible scripts.

--------------------------------------------
Configure jumpbox server with ansible
Starting:Tue Mar 21 15:52:04 DST 2017
sed: can't read /source/OSSonAzure/ansible/hosts: No such file or directory
./OSSonAzure/1-build-environment.sh: line 202: cd: /source/OSSonAzure/ansible: No such file or directory

Calling command: ansible-playbook  -i /source/OSSonAzure/ansible/hosts /source/OSSonAzure/ansible/jumpbox-server-configuration.yml --private-key ~/.ssh/jumpbox_hbg_id_rsa
ERROR! the playbook: /source/OSSonAzure/ansible/jumpbox-server-configuration.yml could not be found

---------------------------------------------
Configure demo template values file
sed: can't read /source/OSSonAzure/vm-assets/DemoEnvironmentTemplateValues: No such file or directory
sed: can't read /source/OSSonAzure/vm-assets/DemoEnvironmentTemplateValues: No such file or directory
Resetting GBBOSSDemo and root passwords based on script values.
Starting:Tue Mar 21 15:52:05 DST 2017
The authenticity of host 'jumpbox-hbg.eastus.cloudapp.azure.com (52.170.217.67)' can't be established.
ECDSA key fingerprint is a0:3f:9c:d7:af:59:56:20:69:df:79:0e:ce:3a:b0:0c.
Are you sure you want to continue connecting (yes/no)? no
Host key verification failed.

**Comment by dansand71** [comment]
Henry - great feedback this has now been fixed.  There is no requirement for a specific directory structure when setting up the jumpbox.  Additionally we have added custom admin naming support.
